### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by Teicu** [dark-warlord14/ffufplus#4]
Hello 

I wonder if it is compatible and works on Mac. I just installed it, all right. But it doesn't seem to give any results. 

Thank you

**Comment by Teicu** [comment]
> VHOST Discovery
> 
> Enter domain for Virtual Host Discovery: google.com
> script.sh: line 30: unfurl: command not found
> script.sh: line 31: ffuf: command not found 

> Parameter Discovery
> 
> Enter URL to discover parameter for: https://google.com
> script.sh: line 22: ffuf: command not found

**Comment by dark-warlord14** [comment]
I would like to you answer few questions before we proceed.

Is golang installed in you system?
You can check this by command
```
which go
```
If you get some output then it is installed.
Next thing is you should check if GOPATH vairable is set properly or not
You can check this by using
```
$GOPATH
```
Let me know if this is set properly, then we can proceed further

**Comment by Teicu** [comment]
Thank you so much for your quick response. 


> Pentest@Teicu ~ % which go
> /usr/local/bin/go
> Pentest@Teicu ~ % $GOPATH
> Pentest@Teicu ~ %

**Comment by dark-warlord14** [comment]
So your GOPATH is not set.
We need to set it up
You need to add following lines in your .bashrc or .bash_profile
```
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```
and then source the file.
This link is for reference: https://sourabhbajaj.com/mac-setup/Go/
After setting this up check if unfurl or ffuf is working or not
And let me know what happens

**Comment by Teicu** [comment]
Hi again 

I added the lines to my .bash_profile 

Now when I type again $GOPATH on my terminal, I get the same like before.  

Pentest@Teicu ~ % $GOPATH
Pentest@Teicu ~ % 

Also, what means "source the file" ?  


<img width="645" alt="Screenshot 2020-04-14 at 13 08 46" src="https://user-images.githubusercontent.com/1572822/79213114-4b5c1c80-7e51-11ea-9ae5-4cdc943349b7.png">

**Comment by dark-warlord14** [comment]
als try addding the same to .bashrc 

and then run
```
source ~/.bashrc
source ~/.bash_profile
```
then try GOPATH again

**Comment by Teicu** [comment]
Hi 

Now works like a charm 

Thank you so much for helping me out. I sincerely appreciate your generosity! 

Cheers

**Comment by dark-warlord14** [comment]
I am glad I could be of some help. Happy Hacking brother!!!

**Comment by Teicu** [comment]
Just a few errors again :( 

please see the screenshot attached. As you see there is 2k added before all the words in the result


<img width="644" alt="Screenshot 2020-04-14 at 14 27 16" src="https://user-images.githubusercontent.com/1572822/79220199-405ab980-7e5c-11ea-928a-6209eee41eaf.png"> 


also, when I type 5 I get this error: 


> Pentest@Teicu ffufplus % bash script.sh
> 
> ffuf on Steroids
> 
> 1) Directory BruteForcing  4) Parse waybackurls
> 2) Parameter Discovery	   5) Beast Mode
> 3) VHOST Discovery
> 
> Select one of the options from above : 5
> Beast Mode ON
> 
> 
> 
> 
> cat: ffuf/*: No such file or directory
> usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
> 	[-e pattern] [-f file] [--binary-files=value] [--color=when]
> 	[--context[=num]] [--directories=action] [--label] [--line-buffered]
> 	[--null] [pattern] [file ...]
> rm: ffuf: is a directory
> rm: -r: No such file or directory
> 
> Done. Result is stored in result_beast.txt
> Pentest@Teicu ffufplus % bash script.sh

**Comment by dark-warlord14** [comment]
What about other modules?
I don't have macOS so I have tested this only on linux.
Can you try the tool on any Ubuntu VPS?
That will be better because I cant exactly tell what is causing this error
